version: "3.8"

services:
  web:
    container_name: modern_network
    image: nginx
    ports:
      - "8082:80"
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8088:80"
    environment:
      - PMA_ARBITRARY=1
    restart: always
